### PR TITLE
multiclass support

### PR DESCRIPTION
**Pull request by Josh-Joseph**
The purpose of this pull request is to provide multiclass support. 

See #7 for more information on the config change. Main changes were in dataset prep and inference -- nothing in train or test had to be touched.

### CODE REVIEW

**Comment by rak5216** [comment]
is this all ready for me @Josh-Joseph, wasn't sure since you posted this yesterday but also mentioned you needed today to work on it?

**Comment by Josh-Joseph** [comment]
testing looked good, for example see attached for a 2class (0+45 and 90) large run (the segmentation wasn't great because I was mostly just testing the color)

inferences_8bit_AS4_S2_P1_L6_2560_1750_2160_segmentation-model-large-2class_20191124T150015Z_output_8bit_AS4_S2_P1_L6_2560_1750_2160-1000

**Comment by Josh-Joseph** [comment]
I also implemented the bit you mentioned in slack of: if two classes are > threshold, color it the highest valued one

**Comment by rak5216** [comment]
awesome!! so all clear for me to review? @Josh-Joseph

**Comment by Josh-Joseph** [comment]
yep yep

**Comment by Josh-Joseph** [comment]
this all look good to you Reed? If so I'll do the merge

**Comment by rak5216** [comment]
I think it looks good, my demo runs haven't finished yet (on train step) but i think it's safe to merge since you got it to work. In `infer_seg`, i swapped the order of blue and yellow so blue is first, because that's how we color the dmg. 0, 45, 90 is blue, yellow, red. hope that's okay

**Comment by Josh-Joseph** [comment]
The swap is definitely okay to do -- my apologies, didn't realize you still had a run going for this. Let me know when that finishes and looks good. No rush on my end to merge this, would be much cleaner to fix issues if they appear for you before we merge.

**Comment by rak5216** [comment]
@Josh-Joseph Just thinking about two cases which I am not sure how are handled, one of which we mentioned prior:

1-What happens if a scan doesn't contain one of the classes? I believe we said this should be fine in train/test/infer due to the softmax mechanism, and that scan with a missing class just won't have a high probability inferred for that class (hopefully). I think nothing should break in train or test either. In prepare dataset, i guess if a scan doesn't have class_2 say, then would the created mask for class_2 just be all 0's, assuming the each mask for multi-class is binary?

2-What happens if a training scan annotated stack has a GV not captured in any class declared? In this case, we should treat the undeclared but present GV as background (0), not sure if that's built-in already.

**Comment by rak5216** [comment]
Also, sorry I'm running big workflows that may take more than a week in one or two cases. I should've down-sampled like you probably just to verify. I'm okay if we close this early then re-open if needed

**Comment by Josh-Joseph** [comment]
> 1-What happens if a scan doesn't contain one of the classes? I believe we said this should be fine in train/test/infer due to the softmax mechanism, and that scan with a missing class just won't have a high probability inferred for that class (hopefully). I think nothing should break in train or test either. In prepare dataset, i guess if a scan doesn't have class_2 say, then would the created mask for class_2 just be all 0's, assuming that each mask for multi-class is binary?

Agreed - I don't think anything breaks here. It'll just be all 0s for that class -- which I think is the desired behavior we'd want

> 
> 2-What happens if a training scan annotated stack has a GV not captured in any class declared? In this case, we should treat the undeclared but present GV as background (0), not sure if that's built-in already.

This is effectively what happens -- the masks are computed based on GV equality so for a class with GV in {100, 150} it'll only match one of those two values (meaning it'll put 1s in those locations on the mask and zeros everywhere else). The locations that didn't match those two values could be anything.

**Pull request merged**
